@node External protocols
@chapter External protocols

@menu
* Packages::
* Basic features::
* Ordinary reader features::
* Readtable features::
* Parse result construction features::
* CST reader features::
@end menu

@node Packages
@section Packages

@menu
* Package for basic features::
* Package for ordinary reader features::
* Package for readtable features::
* Package for parse result construction features::
* Package for CST features::
@end menu

@node Package for basic features
@subsection Package for basic features

The package for basic features such as customizable source location
construction is named @t{eclector.base}.  Although this package does not
shadow any symbol in the @t{common-lisp} package, we still recommend the
use of explicit package prefixes to refer to symbols in this package.

@node Package for ordinary reader features
@subsection Package for ordinary reader features

The package for ordinary reader features is named
@t{eclector.reader}.  To use features of this package, we
recommend the use of explicit package prefixes, simply because this
package shadows and exports names that are also exported from the
@t{common-lisp} package.  Importing this package will likely
cause conflicts with the @t{common-lisp} package otherwise.

@node Package for readtable features
@subsection Package for readtable features

@cindex readtable

The package for readtable-related features is named
@t{eclector.readtable}.  To use features of this package, we
recommend the use of explicit package prefixes, simply because this
package shadows and exports names that are also exported from the
@t{common-lisp} package.  Importing this package will likely
cause conflicts with the @t{common-lisp} package otherwise.

@node Package for parse result construction features
@subsection Package for parse result construction features

@cindex parse result

The package for features related to the creation of client-defined parse
results is named @t{eclector.parse-result}.  To use features of this
package, we recommend the use of explicit package prefixes, simply
because this package shadows and exports names that are also exported
from the @t{common-lisp} package.  Importing this package will likely
cause conflicts with the @t{common-lisp} package otherwise.

@node Package for CST features
@subsection Package for CST features

@cindex parse result
@cindex concrete syntax tree

The package for features related to the creation of concrete syntax
trees is named @t{eclector.concrete-syntax-tree}.  To use features of
this package, we recommend the use of explicit package prefixes, simply
because this package shadows and exports names that are also exported
from the @t{common-lisp} package.  Importing this package will likely
cause conflicts with the @t{common-lisp} package otherwise.

@node Basic features
@section Basic features

@cindex client
@cindex source location

In this section, symbols written without package marker
are in the @t{eclector.base} package
(@pxref{Package for basic features}).

This package provides the mechanism that enables clients to customize
the behavior of the reader.  Furthermore this package provides a
protocol for customizing a particular aspect of the behavior, namely the
construction of source positions and source ranges.  @sysname{} uses
source positions and source ranges in signaled conditions and parse
results (@pxref{Parse result construction features}).

@defclassa {stream-position-condition,eclector.base}

This condition type is the supertype of all conditions which are
signaled by @sysname{} functions.  An instance of this condition type
stores an approximate position in an input stream and an offset from
that position.  The condition is associated with the stream content at
the designated position and offset.  The position uses a representation
which is controlled by the respective client by adding a method on the
@t{source-position} generic function.  The offset indicates a distance
in characters which must be added to the approximate position to produce
the exact position.
@end deftp

@defgena {stream-position,eclector.base} condition

This generic function can be called by clients in order to obtain the
approximate position in the input stream to which @var{condition}
pertains.  The type and interpretation of the returned object depend on
the client, namely the presence of client-specific methods on the
@t{source-position} generic function.  The information returned by the
functions @t{position-offset} and @t{range-length} can be used to refine
the approximate position and compute a range in the input stream
respectively.

Applicable methods exist for all conditions of type
@t{stream-position-condition}.
@end deffn

@defgena {position-offset,eclector.base} condition

This generic function is called in order to compute the exact position
(or start of a range) in the input stream to which @var{condition}
pertains by refining the approximate position obtained by calling
@t{stream-position}.  The returned value is an integer (possibly
negative) which indicates the offset in characters from the approximate
position to the exact position.  Since the representation of the
approximate position is chosen by the client, applying the offset to
that position in a suitable way is also the responsibility of the
client.  Assuming the object returned by @t{(stream-position
@var{condition})} is suitable for arithmetic, the exact position is
@math{stream-position + position-offset}.

Applicable methods exist for all conditions of type
@t{stream-position-condition}.
@end deffn

@defgena {range-length,eclector.base} condition

This generic function is called in order to compute the length of the
range in the input stream to which @var{condition} pertains.  The
returned value is a non-negative integer which indicates the length of
the range in characters.  Therefore, assuming the object returned by
@t{(stream-position @var{condition})} is suitable for arithmetic, the
range covers input the positions @math{[start, start + range-length]}
where @math{start = stream-position + position-offset}.

Applicable methods exist for all conditions of type
@t{stream-position-condition}.
@end deffn

@defvara {*client*,eclector.base}

This variable is used by several generic functions which are called by
@t{eclector.reader:read}.  The default value of the variable is @t{nil}.
Clients that want to override or extend the default behavior of some
generic function of @sysname{} should bind this variable to some
standard object and provide a method on that generic function,
specialized to the class of that standard object.
@end defvar

@defgena {source-position,eclector.base} client stream

This generic function is called in order to determine the current
position in @var{stream}.  @sysname{} does not inspect or manipulate the
objects returned by this generic function beyond storing them in
signaled conditions and passing them as arguments to the
@t{make-source-range} generic function.  A client is therefore free to
define methods on this generic function that return arbitrary objects.

The default method on this generic function calls @t{cl:file-position}.
@end deffn

@defgena {make-source-range,eclector.base} client start end

This generic function is called in order to turn the source positions
@var{start} and @var{end} into a range representation suitable
for @var{client}.  The returned representation designates the range
of input characters from and including the character at position
@var{start} to but not including the character at position
@var{end}.  The default method returns
@code{(cons @var{start} @var{end})}.
@end deffn

@node Ordinary reader features
@section Ordinary reader features

@cindex parse result
@cindex source tracking

In this section, symbols written without package marker are in the
@t{eclector.reader} package
(@pxref{Package for ordinary reader features})

The features provided in this package fall into two categories:
@itemize
@item
The functions @t{read}, @t{read-preserving-whitespace},
@t{read-from-string} and @t{read-delimited-list} which, together with
standard special variables, replicate the interface of the standard
@commonlisp{} reader (except functions related to readtables which @sysname{}
provides separately, @pxref{Readtable features}).  These functions are
discussed in the section @ref{@commonlisp{} reader compatible interface}.

@item
The second category is comprised of the @t{eclector.base:*client*}
special variable and a collection of protocols which allow customizing
the behavior of the reader by defining methods specialized to a
particular client on the generic functions of the protocols.
@end itemize

@float Figure,fig:read-call-sequence-ordinary
@center @image{read-call-sequence-ordinary,15cm}
@caption{Functions and typical function call sequences.  Solid arrows
represent calls, dashed arrows represent returns from function calls.
Labels above arrows represent arguments and return values.}
@end float

@ref{fig:read-call-sequence-ordinary} illustrates the categorization
into the @commonlisp{} reader compatible interface and the extensible
behavior protocol as well as typical function call patterns that arise
when the functions @t{read}, @t{read-preserving-whitespace},
@t{read-from-string} and @t{read-delimited-list} are called by client
code.

@menu
* @commonlisp{} reader compatible interface::
* Reader behavior protocol::
* Reader state protocol::
* Labeled objects and references::
* S-expression creation and quasiquotation::
* Readtable initialization::
@end menu

@node @commonlisp{} reader compatible interface
@subsection @commonlisp{} reader compatible interface

The following functions are like their standarad @commonlisp{}
counterparts with the two differences that their names are symbols in
the @t{eclector.reader} package and that their behavior can deviate from
that of the standard reader depending on the value of the
@t{eclector.base:*client*} variable.

@deffuna {read,eclector.reader} @optional (input-stream @t{*standard-input*})@
  (eof-error-p @t{t})@
  (eof-value @t{nil})@
  (recursive-p @t{nil})

This function is the main entry point for the ordinary reader.  It is
entirely compatible with the standard @commonlisp{} function with the same
name.
@end deffn

@deffuna {read-preserving-whitespace,eclector.reader} @optional (input-stream @t{*standard-input*})@
  (eof-error-p @t{t})@
  (eof-value @t{nil})@
  (recursive-p @t{nil})

This function is entirely compatible with the standard @commonlisp{}
function with the same name.
@end deffn

@deffuna {read-from-string,eclector.reader} string @optional@
  (eof-error-p @t{t})@
  (eof-value @t{nil})@
  @pkey@
  (start @t{0})@
  (end @t{nil})@
  (preserve-whitespace @t{nil})

This function is entirely compatible with the standard @commonlisp{}
function with the same name.
@end deffn

@deffuna {read-delimited-list,eclector.reader} char @optional@
  (input-stream @t{*standard-input*})@
  (recursive-p @t{nil})

This function is entirely compatible with the standard @commonlisp{}
function with the same name.
@end deffn

@node Reader behavior protocol
@subsection Reader behavior protocol

By defining methods on the generic functions of this protocol, clients
can customize the high-level behavior of the reader.

@float Figure,fig:read-call-sequence-customization
@center @image{read-call-sequence-customization,15cm}
@caption{Functions and typical function call sequences terminating on
the right hand side of the diagram at customizable generic functions
which implement aspects of the reader algorithm and standard reader
macros.  Solid arrows represent calls, dashed arrows represent returns
from function calls.  Labels above arrows represent arguments and return
values.}
@end float

@ref{fig:read-call-sequence-customization} illustrates how the
customizable generic functions described in this section are called
through the client interface and the implementation of the reader
algorithm.

@defgena {call-as-top-level-read,eclector.reader} client thunk input-stream@
  eof-error-p eof-value preserve-whitespace-p

This generic function is called by @t{read} if @t{read} is called with a
false value for the @var{recursive-p} parameter.  It calls @var{thunk}
with the necessary context for a global @t{read} call.  @var{thunk}
should read and return an object without consuming any whitespace
following the object.  If @var{preserve-whitespace-p} is false, this
function reads up to one character of whitespace after @var{thunk}
returns.  By default, this function returns the object or
@var{eof-value} returned by @var{thunk} as its sole value.

@quotation Note
This generic function may return more values in addition to the one
described above.  Clients may use this feature to communicate additional
information between methods (@pxref{Parse result construction
features}).  Client defined methods on this generic function should
accept such additional values when calling @var{thunk}, a next method or
@t{read-common} and themselves return the additional values.
@end quotation

The default method on this generic function performs two tasks:
@enumerate
@item
It establishes a context in which labels (@t{#N=}) and references
(@t{#N#}) work.

@item
It realizes the requested @var{preserve-whitespace-p} behavior.
@end enumerate
@end deffn

@defgena {read-common,eclector.reader} client input-stream eof-error-p eof-value

This generic function is called by @t{read}, passing it the value of the
variable @t{eclector.base:*client*} and the corresponding parameters.
By default, this generic function returns the objects as its sole value.

@quotation Note
This generic function may return more values in addition to the one
described above.  Clients may use this feature to communicate additional
information between methods (@pxref{Parse result construction
features}).  Client defined methods on this generic function should
accept such additional values when calling a next method or
@t{read-maybe-nothing} and themselves return the additional values.
@end quotation

Client code can add methods on this function, specializing them to the
client class of its choice.  The actions that @t{read} needs to take for
different values of the parameter @var{recursive-p} have already been
taken before @t{read} calls this generic function.
@end deffn

@defgena {read-maybe-nothing,eclector.reader} client input-stream@
  eof-error-p eof-value

This generic function can be called directly by the client or by the
generic function @t{read-common} to read an object or consume input
without returning an object.  If called directly by the client, the call
has to be in the dynamic scope of a @t{call-as-top-level-read} call.
The function @t{read-maybe-nothing} either

@itemize
@item
encounters the end of input on @var{input-stream} and, depending on
@var{eof-error-p} either signals an error or returns the values
@var{eof-value} and @t{:eof}

@item
or reads one or more whitespace characters an returns the values @t{nil}
and @t{:whitespace}

@item
or reads an object.  If @t{*read-suppress*} is true, the function
returns nil and @t{:suppress}.  Otherwise it returns the object and
@t{:object}.

@item
or consumes a macro character and the characters consumed by the
associated reader macro function if that reader macro function does not
return a value.  In this case the function returns @t{nil} and
@t{:skip}.
@end itemize
@end deffn

@quotation Note
This generic function may return more values in addition to the ones
described above.  Clients may use this feature to communicate additional
information between methods (@pxref{Parse result construction
features}).  Client defined methods on this generic function should
accept such additional values when calling a next method and themselves
return the additional values.
@end quotation

@defgena {note-skipped-input,eclector.reader} client input-stream reason

This generic function is called whenever the reader skips some input
such as a comment or a form that must be skipped because of a reader
conditional.  It is called with the value of the variable
@t{eclector.base:*client*}, the input stream from which the input is
being read and an object indicating the reason for skipping the input.
The default method on this generic function does nothing.  Client code
can supply a method that specializes to the client class of its choice.

When this function is called, the stream is positioned immediately
@emph{after} the skipped input.  Client code that wants to know both
the beginning and the end of the skipped input must remember the
stream position before the call to @t{read} was made as well as
the stream position when the call to this function is made.
@end deffn

@defvara {*skip-reason*,eclector.reader}

This variable is used by the reader to determine why a range of input
characters has been skipped.  To this end, internal functions of the
reader as well as reader macros can set this variable to a suitable
value before skipping over some input.  Then, after the input has been
skipped, the generic function @t{note-skipped-input} is called
with the value of the variable as its @var{reason} argument.

As an example, the method on @t{note-skipped-input} specialized to
@t{eclector.parse-result:parse-result-client} relays the reason and
position information to the client by calling the
@t{eclector.parse-result:make-skipped-input-result} generic function
(@pxref{Parse result construction features}).
@end defvar

@defgena {read-token,eclector.reader} client input-stream eof-error-p@
  eof-value

This generic function is called by @t{read-common} when it has
been detected that a token should be read.  This function is
responsible for accumulating the characters of the token and then
calling @t{interpret-token} (see below) in order to create and
return a token.
@end deffn

@defgena {interpret-token,eclector.reader} client input-stream token@
  escape-ranges

This generic function is called by @t{read-token} in order to
create a token from accumulated token characters.  The parameter
@var{token} is a string containing the characters that make up the
token.  The parameter @var{escape-ranges} indicates ranges of
characters read from @var{input-stream} and preceded by a character
with single-escape syntax or delimited by characters with
multiple-escape syntax.  Values of @var{escape-ranges} are lists of
elements of the form @t{(@var{start}\ .\ @var{end})} where
@t{@var{start}} is the index of the first escaped character
and @t{@var{end}} is the index @emph{following} the last
escaped character.  Note that @t{@var{start}} and
@t{@var{var}} can be identical indicating no escaped
characters.  This can happen in cases like @t{a||b}.  The
information conveyed by the @var{escape-ranges} parameter is used
to convert the characters in @var{token} according to the
@emph{readtable case} of the current readtable before a token is
constructed.
@end deffn

@defgena {check-symbol-token,eclector.reader} client@
  input-stream token escape-ranges@
  position-package-marker-1 position-package-marker-2

This generic function is called by the default method on
@t{interpret-token} when the syntax of the token corresponds to that of
a symbol.  This function checks the syntactic validity of the symbol
token and signals an error in case of a syntax error.  If there are no
syntax errors (or error recovery has been performed, @pxref{Recovering
from errors}), this function returns three values:
@enumerate
@item
@var{token} or a value derived from @var{token} by error recovery
operations.

@item
@var{position-package-marker-1} or a value derived from
@var{position-package-marker-1} by error recovery operations.

@item
@var{position-package-marker-2} or a value derived from
@var{position-package-marker-2} by error recovery operations.
@end enumerate

The parameter @var{input-stream} is the input stream from which the
characters were read.  The parameter @var{token} is a string that
contains all the characters of the token.  The parameter
@var{escape-ranges} indicates ranges within @var{token} that were
preceded by a character with single-escape syntax or delimited by
characters with multiple-escape syntax.  The parameter
@var{position-package-marker-1} contains the index into @var{token} of
the first package marker, or @t{nil} if the token contains no package
markers.  The parameter @var{position-package-marker-2} contains the
index into @var{token} of the second package marker, or @t{nil} if the
token contains no package markers or only a single package marker.

The default method on this generic function checks the positions of the
package markers taking into account escape ranges.  The method signals
errors and allows error recovery as described above.
@end deffn

@defgena {interpret-symbol-token,eclector.reader} client@
  input-stream token position-package-marker-1@
  position-package-marker-2

This generic function is called by the default method on
@t{interpret-token} when the syntax of the token corresponds to
that of a valid symbol.  The parameter @var{input-stream} is the
input stream from which the characters were read.  The parameter
@var{token} is a string that contains all the characters of the
token.  The parameter @var{position-package-marker-1} contains the
index into @var{token} of the first package marker, or @t{nil}
if the token contains no package markers.  The parameter
@var{position-package-marker-2} contains the index into
@var{token} of the second package marker, or @t{nil} if the
token contains no package markers or only a single package marker.

The default method on this generic function calls
@t{interpret-symbol} (see below) with a symbol name string and a
package indicator.
@end deffn

@defgena {interpret-symbol,eclector.reader} client input-stream@
  package-indicator symbol-name internp

This generic function is called by the default method on
@t{interpret-symbol-token} as well as the default
@t{#:} reader macro function to resolve a symbol name string and
a package indicator to a representation of the designated symbol.  The
parameter @var{input-stream} is the input stream from which
@var{package-indicator} and @var{symbol-name} were read.  The
parameter @var{package-indicator} is a either

@itemize
@item
a string designating the package of that name

@item
the keyword @t{:current} designating the current package

@item
the keyword @t{:keyword} designating the keyword package

@item
@t{nil} to indicate that an uninterned symbol should be created
@end itemize

The @var{symbol-name} is the name of the desired symbol.

The default method uses @t{cl:find-package} (or
@t{cl:*package*} when @var{package-indicator} is
@t{:current}) to resolve @var{package-indicator} followed by
@t{cl:find-symbol} or @t{cl:intern}, depending on
@var{internp}, to resolve @var{symbol-name}.

A second method which is specialized on @var{package-indicator}
being @t{nil} uses @t{cl:make-symbol} to create uninterned
symbols.
@end deffn

@defgena {call-reader-macro,eclector.reader} client input-stream char@
  readtable

This generic function is called when the reader has determined that
some character is associated with a reader macro.  The parameter
@var{char} has to be used in conjunction with the
@var{readtable} parameter to obtain the macro function that is
associated with the macro character.  The parameter
@var{input-stream} is the input stream from which the reader macro
function will read additional input to accomplish its task.

The default method on this generic function simply obtains the reader
macro function for @var{char} from @var{readtable} and calls it,
passing @var{input-stream} and @var{char} as arguments.  The
default method therefore does the same thing that the standard
@commonlisp{} reader does.
@end deffn

@defgena {find-character,eclector.reader} client designator

This generic function is called by the default @t{#\} reader macro
function to find a character.  @var{designator} is either
@itemize
@item
a @t{string} that is the name of the character to be found with single
and multiple escapes removed, but with the case of all characters as it
was in the input.

@item
or a character designating itself.
@end itemize
The function has to either return the character designated by
@var{designator} or @t{nil} if no such character exists.

If @var{designator} is a @t{string}, it is the responsibility of the
client to disregard the case of characters in @var{designator}, for
example by producing an uppercase string from @var{designator} before
looking up the designated character.

A default method on this generic function that is not specialized to any
particular client but is specialized to @var{designator} being a
@t{string} recognizes the mandatory character names listing in HyperSpec
Section 13.1.7 Character Names.  Another default method on this generic
function that is not specialized to any particular client but is
specialized to @var{designator} being a @t{character} just returns
@var{designator}.
@end deffn

@defgena {make-structure-instance,eclector.reader} client name initargs

This generic function is called by the default @t{#S} reader
macro function to construct structure instances.  @var{name} is a
symbol naming the structure type of which an instance should be
constructed.  @var{initargs} is a list the elements of which
alternate between string designators naming structure slots and values
for those slots.

It is the responsibility of the client to coerce the string
designators to symbols as if by
@code{(intern (string slot-name) (find-package 'keyword))}
as described in the @commonlisp{} specification.

There is no default method on this generic function since there is no
portable way to construct structure instances given only the name of
the structure type.
@end deffn

@defgena {call-with-current-package,eclector.reader} client thunk@
  package-designator

@quotation Warning
This generic function is deprecated as of @sysname{} 0.9 and will be
removed in a future version.  Please use the generic function
@t{eclector.reader:call-with-state-value} with the aspect designator
@t{'cl:*package*} instead (@pxref{Reader state protocol} for more
information on the reader state protocol).
@end quotation

This generic function is called by the reader when input has to be
read with a particular current package.  This is currently only the
case in the @t{#+} and @t{#-} reader macro functions which
read feature expressions in the keyword package.  @var{thunk} is a
function that should be called without arguments.
@var{package-designator} designates the package that should be the
current package around the call to @var{thunk}.

The default method on this generic function simply binds
@t{cl:*package*} to the result of
@code{(cl:find-package @var{package-designator})}
around calling @var{thunk}.
@end deffn

@defgena {evaluate-expression,eclector.reader} client expression

This generic function is called by the default @t{#.} reader
macro function to perform read-time evaluation.  @var{expression}
is the expression that should be evaluated as it was returned by a
recursive @t{read} call and potentially influenced by
@var{client}.  The function has to either return the result of
evaluating @var{expression} or signal an error.

The default method on this generic function simply returns the result
of @code{(cl:eval @var{expression})}.
@end deffn

@defgena {check-feature-expression,eclector.reader} client@
  feature-expression

This generic function is called by the default @t{#+} and
@t{#-} reader macro functions to check the well-formedness of
@var{feature-expression} which has been read from the input stream
before evaluating it.  For compound expressions, only the outermost
expression is checked regarding the atom in operator position and its
shape -- child expressions are not checked.  The function returns an
unspecified value if @var{feature-expression} is well-formed and
signals an error otherwise.

The default method on this generic function accepts standard
@commonlisp{} feature expression, i.e. expressions recursively
composed of symbols, @t{:not}-expressions,
@t{:and}-expressions and @t{:or}-expressions.
@end deffn

@defgena {evaluate-feature-expression,eclector.reader} client@
 feature-expression

This generic function is called by the default @t{#+} and
@t{#-} reader macro functions to evaluate
@var{feature-expression} which has been read from the input stream.
The function returns either true or false if
@var{feature-expression} is well-formed and signals an error
otherwise.

For compound feature expressions, the well-formedness of child
expressions is not checked immediately but lazily, just before the child
expression in question is evaluated in a subsequent
@t{evaluate-feature-expression} call.  This allows expressions like
@code{#+(and my-cl-implementation (special-feature a b)) @var{form}} to
be read without error when the @t{:my-cl-implementation} feature is
absent.

The default method on this generic function first calls
@t{check-feature-expression} to check the well-formedness of
@var{feature-expression}.  It then evaluates
@var{feature-expression} according to standard @commonlisp{}
semantics for feature expressions.
@end deffn

@node Reader state protocol
@subsection Reader state protocol

@cindex reader state
@cindex aspect, reader state

The reader state protocol consists of generic functions which the reader
and the client call to query and modify the values of reader state
@emph{aspects}.  Each aspect is named by a symbol and holds a current
value and has a stack of shadowed values like a special variable.
Aspects roughly correspond to the reader control variables defined in
the @commonlisp{} specification.  @sysname{} defines the following
aspects:

@anchor{table:minimal-reader-state-aspects}
@table @code
@item cl:*readtable*

Like the @t{cl:*readtable*} special variable, this aspects controls the
readtable object in which the reader looks up the syntax types of
characters, the case conversion mode as well as reader macros.  By
default, values of this aspect must satisfy the
@t{eclector.readtable:readtablep} predicate.

@item cl:*package*

Like the @t{cl:*package*} special variable, this aspects controls the
package which the reader uses when it looks up or interns symbols in the
current package.

@item cl:*read-suppress*

Like the @t{cl:*read-suppress*} special variable, this aspect controls
whether the reader skips over expressions without detailed parsing.

@item cl:*read-eval*

Like the @t{cl:*read-eval*} special variable, this aspect controls
whether the reader evaluates expressions in @t{#.} constructs.

@item cl:*features*

Like the @t{cl:*features*} special variable, this aspect controls the
evaluation of features in feature expressions in @t{#+} and @t{#-}
constructs.

@item cl:*read-base*

Like the @t{cl:*read-base*} special variable, this aspect controls the
interpretation of tokens by the reader as being integers or ratios.

@item cl:*read-default-float-format*

Like the @t{cl:*read-default-float-format*} special variable, this
aspect controls the floating-point format that the reader uses for
floating-point numbers without exponent marker or the default exponent
marker.

@end table

@defgena{valid-state-value-p,eclector.reader} client aspect value

This generic function is called by the reader to determine whether
@var{value} is a valid value for the reader state aspect designated by
@var{aspect}.  The generic function returns true if, according to
@var{client}, @var{value} is a valid value for the reader state aspect
designated by @var{aspect}.  @var{aspect} must designate a reader state
aspect that is recognized by @var{client}.  At least the aspects listed
in the @ref{table:minimal-reader-state-aspects,,minimal reader state
aspects table} must be recognized by any client.

With the exceptions of @t{cl:*readtable*} and @t{cl:*package*}, the
default methods on this generic function recognize state aspects and
implement type restrictions informed by the @commonlisp{} specification:
@multitable @columnfractions .3 .7
@headitem Aspect                             @tab Type
@item     @t{cl:*readtable*}                 @tab @t{(satisfies eclector.readtable:readtablep)}
@item     @t{cl:*package*}                   @tab @t{(or cl:package cl:symbol cl:string cl:character)} (package designator)
@item     @t{cl:*read-suppress*}             @tab @t{t} (generalized Boolean)
@item     @t{cl:*read-eval*}                 @tab @t{t} (generalized Boolean)
@item     @t{cl:*features*}                  @tab @t{list} (proper list)
@item     @t{cl:*read-base*}                 @tab @t{(integer 2 36)} (radix)
@item     @t{cl:*read-default-float-format*} @tab @t{(member short-float single-float double-float long-float)}
@end multitable
@end deffn

@defgena{state-value,eclector.reader} client aspect

Return the current value of the reader state aspect designated by
@var{aspect}.

@var{aspect} must designate a reader state aspect that is recognized by
@var{client}.  At least the aspects listed in the
@ref{table:minimal-reader-state-aspects,,minimal reader state aspects
table} must be recognized by any client.

The @t{cl:*package*} aspect mandates further explanation: When the
client uses only the default methods of the reader state protocol, the
return value of this generic function for the @t{cl:*package*} aspect is
of type @t{cl:package} which is a strict subtype of the type of valid
values for this aspect.  In other words, the defaults coerce package
designators to package objects.
@end deffn

@defgena{call-with-state-value,eclector.reader} client thunk aspect value

Call @var{thunk} with the reader state aspect designated by @var{aspect}
bound to @var{value}.

@var{aspect} must designate a reader state aspect that is recognized by
@var{client}.  At least the aspects listed in the
@ref{table:minimal-reader-state-aspects,,minimal reader state aspects
table} must be recognized by any client.

The following properties must hold:

@itemize
@item
@var{value} has to be a valid value for @var{aspect} in the sense that
@code{(eclector.reader:valid-state-value-p @var{client} @var{aspect}
@var{value})} must return true.

@item
During the call to @var{thunk} and absent any intervening calls to
@t{eclector.reader:call-with-state-value}, the expression
@code{(eclector.reader:state-value @var{client} @var{aspect})} must
evaluate to @var{value}.
@end itemize

When @sysname{} calls this generic function with @t{cl:*package*} as the
value of @var{aspect}, the @var{value} is a always a string designator
and never a package object.  The default method on this generic function
coerces such string designators to package objects so that a subsequent
@t{eclector.reader:state-value} call returns the designated package
object.
@end deffn

@node Labeled objects and references
@subsection Labeled objects and references

@cindex labeled object

@sysname{} includes implementations of the @t{#=} and @t{##} reader
macros and they are present in the default readtable.  One way to
customize the behavior of the reader around the @t{#=} and @t{##} syntax
is replacing the reader macro functions with custom ones but with this
approach the client code has to reimplement a lot of functionality.  As
a finer grained and more composable mechanism for customization,
@sysname{} provides a protocol for implementing and customizing the
behavior of the @t{#=} and @t{##} reader macros, with or without
modifying the readtable.  The remainder of this section describes that
protocol.

To start with a bit of terminology, we call the object created by
reading @t{#@var{N}=@var{expression}} a @dfn{labeled object}. We call
@var{N} the @dfn{label} of the labeled object and the result of reading
@t{@var{expression}} the @dfn{object} of the labeled object.  We say
that @t{#@var{N}=@var{expression}} @dfn{defines} the labeled object and
@t{#@var{N}#} @dfn{references} the labeled object.  We call the
reference @dfn{circular} if @t{#@var{N}#} occurs within
@var{expression}.  Labeled objects are internal to the reader and only
exist during @t{eclector.reader:read} calls: before such a call returns
an object, each labeled object within the returned object is replaced by
its respective final object.  Callers of @t{eclector.reader:read} and
related functions will therefore only ever see the object, never the
labeled object@footnote{Reader macro functions which call
@t{eclector.reader:read} may receive labeled objects under certain
circumstances (@pxref{Circular objects and custom reader macros}).}.

On a technical level, a labeled object is represented as a data type
with a current state and a single (possibly unbound) slot containing the
object.  The following diagrams depicts the possible states of a labeled
object together with input patterns and corresponding transitions:

@float Figure,fig:labeled-object-states
@center @image{labeled-object-states,15cm}
@caption{Possible states of a labeled object and input patterns which
correspond to state transitions.}
@end float

Put differently, a labeled object can be in the following states:

@multitable @columnfractions .5 .3
@headitem State                                          @tab Object slot
@item undefined                                          @tab --
@item defined                                            @tab unbound
@item final                                              @tab the object
@item referenced @emph{(not strictly needed)}            @tab the object
@item circular                                           @tab unbound
@item final (circular)                                   @tab the object
@item referenced (circular) @emph{(not strictly needed)} @tab the object
@end multitable

The distinction between the states @t{final} and @t{referenced} on the
one hand and @t{final (circular)}, and @t{referenced (circular)} on the
other hand is not required for implementing labeled objects.  Those two
pairs of states are therefore collapsed to just @t{final} and @t{final
(circular)} in the remainder of this section.  The following figure and
paragraphs describe generic functions and methods which implement the
creation, registration, lookup and manipulation of labeled objects
according to the reduced set of states:

@float Figure,fig:labeled-object-api-states
@center @image{labeled-object-api-states,12cm}
@caption{Reduced set of states of a labeled object and protocol
functions with corresponding state transitions.}
@end float

In addition to the generic functions referenced in the above diagram,
the generic functions @t{fixup-graph-p}, @t{fixup-graph} and @t{fixup}
are part of the protocol.  Those functions are used to replace labeled
objects with their respective final objects within an object that is
about to be returned to the caller of @t{eclector.reader:read}
@footnote{This fixup processing has to be delayed under certain
circumstances (@pxref{Circular objects and custom reader macros}).}.  To
this end, the @t{#=} reader macro function must inspect and update the
state of the labeled object it is processing after reading
@t{@var{expression}} by calling @t{finalize-labeled-object}.
@t{finalize-labeled-object} decides whether @t{fixup-graph} (see below)
must be called: If after reading @t{@var{expression}} the labeled object
is in state @t{:circular}, @t{@var{expression}} must have contained
circular references and the result of reading it contains labeled
objects that have to be replaced with their respective final objects.
@t{fixup-graph} and @t{fixup} perform this replacement.  This
replacement is performed by recursively traversing objects which are
reachable from the final object of the labeled objects, for example by
visiting the slots of standard objects, and replacing labeled objects
with their respective final object.

In certain cases, the computational complexity of this traversal and
replacement can be rather high, depending on when and how exactly the
traversal is performed: consider an expression of the form
@t{#1=(1 #1# #2=(2 #2# @dots{}))}.  The nested labeled objects in this
expression are all circular and thus require fixing up.  The @t{read}
call for the innermost labeled object, say @t{#100=@dots{}}, returns
first and the fixup processing for the labeled object could be performed
immediately.  The problem is that each of the labeled objects would
be processed in the same manner which would lead to a computation
complexity of @math{O(N M)} where @math{N} is the number of labels and
@math{M} is the number of nodes in the object graph rooted at the object
which is returned by the outermost @t{read} call.  One way to avoid this
problem would be to perform fixup processing only for the outermost
@t{read} call.  The problem with that approach is that only a small
sub-graph of the whole object graph may be circular in which case most
of the work for traversing the whole graph would be wasted.  To address
both problems, @sysname{} allows clients to track the nesting of labeled
objects and fix up sub-graphs which contain multiple nested objects in
one go
(@pxref{Generic-Function eclector.reader|fixup-graph-p, fixup-graph-p}).

@defgena{call-with-label-tracking,eclector.reader} client thunk

This generic function is called by the default method on
@t{call-as-top-level-read} in order to establish a context for tracking
@t{#=} label definitions and @t{##} label references around a call to
@var{thunk}.

The default method on this generic function establishes a context in
which the default @t{#=} and @t{##} reader macro functions can make the
appropriate calls to @t{note-labeled-object}, @t{forget-labeled-object},
@t{find-labeled-object}.
@end deffn

@defgena{note-labeled-object,eclector.reader} client input-stream label@
  parent

This generic function is called by the default @t{#=} reader macro
function to note the definition of a labeled object with label
@var{label} while reading from @var{input-stream}.  The function
creates, registers and returns a representation of the labeled object.
The returned object is registered in the sense that a subsequent call to
@t{find-labeled-object} with arguments @var{client} and @var{label}
returns the same object unless @t{forget-labeled-object} has been called
to unregister the object.

@var{parent} is either @t{nil} or a (previously created) surrounding
labeled object.  The parent labeled object is provided to allow the
client to potentially defer fixup processing for the new labeled object
if the processing for the surrounding labeled object subsumes the
processing for the new labeled object.

Note that, when reading an expression of the form
@t{#@var{N}=@var{object}}, this function is called after reading
@t{#@var{N}=} from @var{input-stream} but before reading
@t{@var{object}}.  Consequently, the created and returned labeled object
is defined but does not have an object associated with it.

The default method on this generic function calls
@t{make-labeled-object} with @var{client}, @var{input-stream} and
@var{label} to create an object of an unspecified type.  The method
registers and returns the created object.  Client code should manipulate
the object only via the generic functions described in this section and
in particular not rely on the object being of a particular type (since
methods on @t{make-labeled-object} specialized to certain client classes
could return unexpected objects).  The default method requires the
context established by the default method on
@t{call-with-label-tracking}.
@end deffn

@defgena{forget-labeled-object,eclector.reader} client label

This generic function is called by the default @t{#=} reader macro
function when @sysname{} reads an invalid labeled object of the form
@t{#@var{N}=#@var{N}#} and the caller chooses to recover from the
resulting error (@pxref{Recovering from errors}).  In that situation,
the remainder of the input is processed as if there had been no labeled
object with label @var{N}.  This function makes the labeled object
undefined so that a subsequent @t{find-labeled-object} call for
@var{label} will return @t{nil}.

The default method on this generic function requires the context
established by the default method on @t{call-with-label-tracking}.
@end deffn

@defgena{find-labeled-object,eclector.reader} client label

This generic function is called by the default @t{##} reader macro
function to look up the previously registered representation of a
labeled object for @var{label}.  The function returns @t{nil} if no such
object has been registered for @var{label} and the registered object
otherwise.

The default method on this generic function requires the context
established by the default method on @t{call-with-label-tracking}.
@end deffn

@defgena{make-labeled-object,eclector.reader} client input-stream label@
  parent

This generic function is called by @t{note-labeled-object} to create and
return a representation of a labeled object with label @var{label}.
@var{parent} is either @t{nil} or a previously created, surrounding
labeled object which allows the client to potentially defer fixup
processing for the new labeled object if the processing for the
surrounding labeled object subsumes the processing.

The default method on this generic function creates and returns an
object of an unspecified type.  Client code should manipulate the object
only via the generic functions @t{labeled-object-state},
@t{finalize-labeled-object} and @t{reference-labeled-object} and in
particular not rely on the object being of a particular type (since
methods on this generic function specialized to certain client classes
could return unexpected objects).
@end deffn

@defgena{labeled-object-state,eclector.reader} client object

This generic function is called by the default @t{#=} reader macro
function to determine the state of @var{object}.  This function returns

@itemize
@item
@t{nil} if @var{object} is not a labeled object

@item
two values if @var{object} is a labeled object: one of the keywords
@t{:defined}, @t{:circular}, @t{:final}, @t{:final/circular} and the
final object stored in @var{object} if the first value is either
@t{:final} or @t{:final/circular} or @t{nil} otherwise.
@end itemize

The following table lists all possible return value shapes:
@multitable @columnfractions .3 .3 .3
@headitem @var{object} is a labeled object @tab First value         @tab Second value
@item no                                   @tab @t{nil}             @tab
@item yes                                  @tab @t{:defined}        @tab @t{nil}
@item yes                                  @tab @t{:circular}       @tab @t{nil}
@item yes                                  @tab @t{:final}          @tab @var{final-object}
@item yes                                  @tab @t{:final/circular} @tab @var{final-object}
@end multitable

The default method on this generic function is applicable to labeled
object representations returned by the default methods on
@t{note-labeled-object} and @t{make-labeled-object}.
@end deffn

@defgena{finalize-labeled-object,eclector.reader} client labeled-object@
  object

This generic function is called by the default @t{#=} reader macro
function after reading a complete labeled object in order to store
@var{object} in @var{labeled-object} and change the state of
@var{labeled-object} to either @t{:final} or @t{:final/circular}.  The
function returns two values: the finalized @var{labeled-object} and the
new state of @var{labeled-object}.

The default method on this generic function is applicable to labeled
object representations returned by the default methods on
@t{note-labeled-object} and @t{make-labeled-object}.
@end deffn

@defgena{reference-labeled-object,eclector.reader} client input-stream@
  labeled-object

This generic function is called by the default @t{##} reader macro
function to process a reference to @var{labeled-object} while reading
from @var{input-stream}.  @var{labeled-object} must be a representation
of a labeled object and has, in the context of the @t{##} reader macro
function, likely been obtained by calling @t{find-labeled-object}.
Depending on the state of @var{labeled-object}, this function returns
either @var{labeled-object} itself or an object that can be returned to
the caller as-is.  In case @var{labeled-object} is returned, it will be
replaced by its associated object later, when @t{fixup-graph} is called.

The default method on this generic function is applicable to labeled
object representations returned by the default methods on
@t{note-labeled-object} and @t{make-labeled-object}.
@end deffn

As briefly mentioned above, the generic functions @t{fixup-graph} and
@t{fixup} traverse and inspect objects in the object graph reachable
from an object that is about to be returned to the caller of
@t{eclector.reader:read}.  In order to distinguish ordinary objects from
labeled objects that act as placeholders in the object graph and must be
replaced with their respective final objects, @t{fixup} methods call
@t{labeled-object-state} on all encountered objects.
@t{labeled-object-state} returns @t{nil} for all objects that are not
labeled objects and @t{:final} for labeled objects which must be
replaced with their final object.

@defgena {fixup-graph-p,eclector.reader} client root-labeled-object

This generic function is potentially called by a method on
@t{finalize-labeled-object} to determine whether the object graph
reachable from the object of @var{root-labeled-object} should be fixed
up by calling @t{fixup-graph} with @var{client} and
@var{labeled-object}.

Multiple default methods on this generic function jointly implement the
following behavior:

@itemize

@item
If @var{root-labeled-object} has a parent labeled object,
@var{root-labeled-object} should not be fixup up immediately (since the
fixup processing for ancestor labeled objects will subsume the fixup
processing for @var{root-labeled-object}).

@item
If @var{root-labeled-object} does not have parent labeled object but has
child labeled objects, @var{root-labeled-object} should be fixed up
immediately.

@item
If @var{root-labeled-object} does not have parent labeled object and is
in state @t{:final/circular}, @var{root-labeled-object} should be fixed
up immediately.
@end itemize
@end deffn

@defgena {fixup-graph,eclector.reader} client root-labeled-object@
 @pkey object-key

This generic function is potentially called after the reader has
constructed an object graph which is reachable from the object of
@var{root-labeled-object} and noticed circular references within this
graph to fix up circular references before the object of
@var{root-labeled-object} is returned to the caller (of @t{read} or
related functions).

@var{object-key} is a function that accepts a labeled object and returns
the object of the labeled object.

The default method on this generic function creates a hash table for
tracking already processed objects and calls @t{fixup} with
@var{client}, the object of @var{root-labeled-object} and the hash table
to recursively process objects in the object graph which is reachable
from the object of @var{root-labeled-object}.
@end deffn

@defgena {fixup,eclector.reader} client object seen-objects

This generic function is potentially called to apply circularity-related
changes to the object constructed by the reader before it is returned to
the caller.  @var{object} is the object that should be modified.
@var{seen-objects} is a @t{eq}-hash table used to track already
processed objects (see below).  A method specialized to a class,
instances of which consists of parts, should modify @var{object} by
scanning its parts for labeled object markers, replacing found labeled
object markers with the respective final object and recursively calling
@t{fixup} for all parts.

To recognize labeled objects which have to be replaced, methods should
call @t{labeled-object-state} on each part of @var{object} and interpret
the returned values as follows: if @t{nil} is returned, the part should
not be replaced but recursively processed.  If @t{:final} is returned as
the first value, the part should be replaced with the final object that
is returned as the second value.  Parts are replaced by mutating
@var{object}.

@t{fixup} is called for side effects -- its return value is ignored.

Default methods specializing the @var{object} parameter to @t{cons},
@t{array}, @t{standard-object} and @t{hash-table} process instances of
those classes in the obvious way.

An unspecialized @t{:around} method queries and updates
@var{seen-objects} to ensure that each object is processed exactly once.
@end deffn

@node S-expression creation and quasiquotation
@subsection S-expression creation and quasiquotation

@cindex function
@cindex quotation
@cindex quasiquotation

@cindex function

@defgena {make-expression,eclector.reader} client kind sub-expression

TODO This generic function is called by the default @t{#'}-reader macro
function to construct a form that applies the @t{function} special
operator to the @var{name} expression.

The default method on this generic function returns a result equivalent
to @code{(list 'common-lisp:function @var{form})}.
@end deffn

TODO describe kinds and default methods

TODO deprecated

@cindex function

@defgena {wrap-in-function,eclector.reader} client name

This generic function is called by the default @t{#'}-reader macro
function to construct a form that applies the @t{function} special
operator to the @var{name} expression.

The default method on this generic function returns a result equivalent
to @code{(list 'common-lisp:function @var{form})}.
@end deffn

@cindex quotation

The following generic functions allow clients to construct
representations of quoted and quasiquoted forms.

@defgena {wrap-in-quote,eclector.reader} client material

This generic function is called by the default @t{'}-reader macro
function to construct a quotation form in which @var{material} is
the quoted material.

The default method on this generic function returns a result
equivalent to @code{(list 'common-lisp:quote @var{material})}.
@end deffn

@cindex quasiquotation

@defgena {wrap-in-quasiquote,eclector.reader} client form

This generic function is called by the default @t{`}-reader macro
function to construct a quasiquotation form in which @var{form} is
the quasiquoted material.

The default method on this generic function returns a result
equivalent to @code{(list 'eclector.reader:quasiquote @var{form})}.
@end deffn

@defgena {wrap-in-unquote,eclector.reader} client form

This generic function is called by the default @t{,}-reader macro
function to construct an unquote form in which @var{form} is the
unquoted material.

The default method on this generic function returns a result
equivalent to @code{(list 'eclector.reader:unquote @var{form})}.
@end deffn

@defgena {wrap-in-unquote-splicing,eclector.reader} client form

This generic function is called by the default @t{,@@}-reader macro
function to construct a splicing unquote form in which @var{form} is the
unquoted material.

The default method on this generic function returns a result
equivalent to
@code{(list 'eclector.reader:unquote-splicing @var{form})}.
@end deffn

Backquote and unquote syntax is forbidden in some contexts such as
multi-dimensional array literals (@t{#A}) and structure literals
(@t{#S}) thus @sysname{} has a mechanism for controlling whether
backquote, unquote or both should be allowed in a given context.
Since custom reader macros may also have to control this aspect,
@sysname{} provides an external protocol:

@defmaca {with-forbidden-quasiquotation,eclector.reader} context@
  @optional@
  (quasiquote-forbidden-p @t{t})@
  (unquote-forbidden-p @t{t})@
  @pbody body

Disallow backquote syntax, unquote syntax or both in @t{read}
functions called during the execution of @var{body}.
@var{context} is a symbol identifying the current context which is
used for error reporting.  A typical value is the name of the reader
macro function in which this macro is used.
@var{quasiquote-forbidden-p} controls whether backquote syntax
should be forbidden.  The value @t{:keep} causes the binding to
remain unchanged.  @var{unquote-forbidden-p} controls whether
unquote syntax should be forbidden.  The value @t{:keep} causes
the binding to remain unchanged.
@end deffn

@node Readtable initialization
@subsection Readtable initialization

@cindex readtable

The standard syntax types and macro character associations used by the
ordinary reader can be set up for any readtable object implementing the
readtable protocol (@pxref{Readtable features}).  The
following functions are provided for this purpose:

@deffuna {set-standard-syntax-types,eclector.reader} readtable

This function sets the standard syntax types in @var{readtable}
(See HyperSpec section 2.1.4.)
@end deffn

@deffuna {set-standard-macro-characters,eclector.reader} readtable

This function sets the standard macro characters in @var{readtable}
(See HyperSpec section 2.4.)
@end deffn

@deffuna {set-standard-dispatch-macro-characters,eclector.reader}@
  readtable

This function sets the standard dispatch macro characters, that is
sharpsign and its sub-characters, in @var{readtable} (See HyperSpec
section 2.4.8.)
@end deffn

@deffuna {set-standard-syntax-and-macros,eclector.reader} readtable

This function sets the standard syntax types and macro characters in
@var{readtable} by calling the above three functions.
@end deffn

@node Readtable features
@section Readtable features

@cindex readtable

In this section, symbols written without package marker are in the
@t{eclector.readtable} package (@pxref{Package for readtable features}).

This package exports two kinds of symbols:

@enumerate
@item
Symbols the names of which correspond to the names of symbols in the
@t{common-lisp} package.  The functions bound to these symbols are
generic versions of the corresponding standard @commonlisp{} functions.
Clients can define custom readtables by defining methods on these
generic functions.

@item
Symbols bound to additional functions and condition types.
@end enumerate

@defgena {readtablep,eclector.readtable} object

This function is the generic version of the standard @commonlisp{}
function @t{cl:readtablep}.  The function returns true if
@var{object} can be used as a readtable in @sysname{} via the
protocol functions in the @t{ecelctor.readtable} package.  The
default method returns @t{nil}.
@end deffn

TODO

@node Parse result construction features
@section Parse result construction features

@cindex client
@cindex parse result

In this section, symbols written without package marker are in the
@t{eclector.parse-result} package (@pxref{Package for parse
result construction features}).

This package provides clients with a reader that behaves similarly to
@t{cl:read} but returns custom parse result objects controlled by
the client.  Some parse results correspond to things like symbols,
numbers and lists that @t{cl:read} would return, while others, if
the client chooses, represent comments and other kinds of input that
@t{cl:read} would discard.  Furthermore, clients can associate
source location information with parse results.

Clients using this package pass a ``client'' object for which methods on
the generic functions described below are applicable to @t{read},
@t{read-preserving-whitespace} or @t{read-from-string}.  Suitable client
classes can be defined by using @t{parse-result-client} as a superclass
and at least defining a method on the generic function
@t{make-expression-result}.

When a client constructs parse results, some of the generic functions
for customizing the behavior of the reader (@pxref{Reader behavior
protocol}) return additional values:

@multitable @columnfractions .25 .15 .3 .3
@headitem Generic function                       @tab Situation    @tab Ordinary values            @tab Extended values

@item @t{eclector.reader:call-as-top-level-read} @tab object       @tab @emph{object}              @tab @emph{object}, @emph{parse result}, @emph{orphan results}
@item @t{eclector.reader:read-common}            @tab object       @tab @emph{object}              @tab @emph{object}, @emph{parse result}
@item @t{eclector.reader:read-maybe-nothing}     @tab object       @tab @emph{object}, @emph{kind} @tab @emph{object}, @emph{kind}, @emph{parse result}

@item @t{eclector.reader:call-as-top-level-read} @tab end of input @tab @var{eof-value}            @tab @var{eof-value}, @emph{orphan results}
@item @t{eclector.reader:read-common}            @tab end of input @tab @var{eof-value}            @tab @var{eof-value}
@item @t{eclector.reader:read-maybe-nothing}     @tab end of input @tab @var{eof-value}, @t{:eof}  @tab @var{eof-value}, @t{:eof}
@end multitable

Note how @t{eclector.reader:call-as-top-level-read} and
@t{eclector.reader:read-common} return fewer values for the ``end of
input'' situation.  This difference in return value count allows the
caller to recognize the ``end of input'' situation even if
@var{eof-value} is an object that could be read such as @t{nil}.  Using
such an @var{eof-value} makes sense for clients which construct parse
results since top-level @t{eclector.parse-result:read} calls return
these parse results so that there is no risk of confusing the chosen
@var{eof-value}, even if something like @t{nil}, with having read a
similar object.

@float Figure,fig:read-call-sequence-parse-result
@center @image{read-call-sequence-parse-result,15cm}
@caption{Functions and typical function call sequences.  Solid arrows
represent calls, dashed arrows represent returns from function calls.
Labels above arrows represent arguments and return values.  Differences
from the non-parse result version are highlighted with bold text.}
@end float

@ref{fig:read-call-sequence-parse-result} shows typical function call
patterns, including ordinary and additional return values, that arise
when the functions @t{read}, @t{read-preserving-whitespace},
@t{read-from-string} and @t{read-delimited-list} are called by client
code.

@deffuna {read,eclector.parse-result} client @optional@
  (input-stream @t{*standard-input*})@
  (eof-error-p @t{t})@
  (eof-value @t{nil})

This function is the main entry point for this variant of the reader.
It is in many ways similar to the standard @commonlisp{} function
@t{cl:read}.  The differences are:

@itemize
@item
A client instance must be supplied as the first argument.

@item
The first return value, unless @var{eof-value} is returned, is an
arbitrary parse result object created by the client, not generally the
read object.

@item
The second return value, unless @var{eof-value} is returned, is a list
of ``orphan'' results.  These results are return values of
@t{make-skipped-input-result} and arise when skipping input at the
toplevel such as comments which are not lexically contained in lists:
@t{#|orphan|# (#|not orphan|#)}.

@item
The function does not accept a @var{recursive} parameter since it sets
up a dynamic environment in which calls to @t{eclector.reader:read}
behave suitably.
@end itemize
@end deffn

@deffuna {read-preserving-whitespace,eclector.parse-result} client@
  @optional (input-stream @t{*standard-input*})@
  (eof-error-p @t{t})@
  (eof-value @t{nil})

This function is similar to the standard @commonlisp{} function
@t{cl:read-preserving-whitespace}.  The differences are the same
as described above for @t{read} compared to @t{cl:read}.
@end deffn

@deffuna {read-from-string,eclector.parse-result} client string@
   @optional@
  (eof-error-p @t{t})@
  (eof-value @t{nil})@
  @pkey@
  (start @t{0})@
  (end @t{nil})@
  (preserve-whitespace @t{nil})

This function is similar to the standard @commonlisp{} function
@t{cl:read-from-string}.  The differences are:

@itemize
@item
A client instance must be supplied as the first argument.

@item
The first return value, unless @var{eof-value} is returned, is an
arbitrary parse result object created by the client, not generally the
read object.

@item
The @emph{third} return value, unless @var{eof-value} is returned, is a
list of ``orphan'' results (Described above).
@end itemize
@end deffn

@defclassa {parse-result-client,eclector.parse-result}

This class should generally be used as a superclass for client classes
using this package.
@end deftp

@defgena {make-expression-result,eclector.parse-result} client result@
  children source

This generic function is called in order to construct a parse result
object.  The value of the @var{result} parameter is the raw object read.
The value of the @var{children} parameter is a list of already
constructed parse result objects representing objects read by recursive
@t{read} calls.  The value of the @var{source} parameter is a source
range, as returned by @t{eclector.base:make-source-range} and
@t{eclector.base:source-position} delimiting the range of characters
from which @var{result} has been read.

This generic function does not have a default method since the purpose
of the package is the construction of @emph{custom} parse results.
Thus, a client must define a method on this generic function.
@end deffn

@defgena {make-skipped-input-result,eclector.parse-result} client@
  stream reason source

This generic function is called after the reader skipped over a range
of characters in @var{stream}.  It returns either @t{nil} if
the skipped input should not be represented or a client-specific
representation of the skipped input.  The value of the @var{source}
parameter designates the skipped range using a source range
representation obtained via @t{make-source-range} and
@t{source-position}.

Reasons for skipping input include comments, the @t{#+} and
@t{#-} reader macros and @t{*read-suppress*}.  The
aforementioned reasons are reflected by the value of the
@var{reason} parameter as follows:

@multitable @columnfractions .5 .5
@headitem Input                            @tab Value of the @var{reason} parameter
@item Comment starting with @t{;}          @tab @t{(:line-comment . 1)}
@item Comment starting with @t{;;}         @tab @t{(:line-comment . 2)}
@item Comment starting with @math{n} @t{;} @tab @t{(:line-comment . @math{n})}
@item Comment delimited by @t{#|} @t{|#}   @tab @t{:block-comment}
@item @t{#+@emph{false-expression}}        @tab @t{(:sharpsign-plus . @emph{false-expression})}
@item @t{#-@emph{true-expression}}         @tab @t{(:sharpsign-minus . @emph{true-expression})}
@item @t{*read-suppress*} is true          @tab @t{*read-suppress*}
@item A reader macro returns no values     @tab @t{:reader-macro}
@end multitable

The default method returns @t{nil}, that is the skipped input is
not represented as a parse result.
@end deffn

@node CST reader features
@section CST reader features

@cindex parse result
@cindex concrete syntax tree

In this section, symbols written without package marker are in the
@t{eclector.concrete-syntax-tree} package (@pxref{Package for CST
features}).

@deffuna {read,eclector.concrete-syntax-tree} @optional@
  (input-stream @t{*standard-input*})@
  (eof-error-p @t{t})@
  (eof-value @t{nil})

This function is the main entry point for the CST reader.  It is
mostly compatible with the standard @commonlisp{} function
@t{cl:read}.  The differences are:

@itemize
@item
The return value, unless @var{eof-value} is returned, is an instance of
a subclass of @t{concrete-syntax-tree:cst}.

@item
The function does not accept a @var{recursive} parameter since it sets
up a dynamic environment in which calls to @t{eclector.reader:read}
behave suitably.
@end itemize
@end deffn

@deffuna {read-preserving-whitespace,eclector.concrete-syntax-tree}@
  @optional (input-stream @t{*standard-input*}) (eof-error-p @t{t})@
  (eof-value @t{nil})

This function is similar to the standard @commonlisp{} function
@t{cl:read-preserving-whitespace}.  The differences are the same
as described above for @t{read} compared to @t{cl:read}.
@end deffn

@deffuna {read-from-string,eclector.concrete-syntax-tree} string@
  @optional@
  (eof-error-p @t{t})@
  (eof-value @t{nil})@
  @pkey@
  (start @t{0})@
  (end @t{nil})@
  (preserve-whitespace @t{nil})

This function is similar to the standard @commonlisp{} function
@t{cl:read-from-string}.  The differences are the same as
described above for @t{read} compared to @t{cl:read}.
@end deffn
